// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func Setup() (*MainStuff, error) {
	dbConnString := NewDBConnString()
	dbDriverName := NewDBDriverName()
	widgetController := NewWidgetController()
	router := NewWidgetRouter(widgetController)
	mainStuff, err := NewMainStuff(dbConnString, dbDriverName, router)
	if err != nil {
		return nil, err
	}
	return mainStuff, nil
}
