// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func Setup() (*MainStuff, error) {
	dbConnString := NewDBConnString()
	dbDriverName := NewDBDriverName()
	mainStuff, err := NewMainStuff(dbConnString, dbDriverName)
	if err != nil {
		return nil, err
	}
	return mainStuff, nil
}
