// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWidgets(t *testing.T) {
	t.Parallel()

	query := Widgets()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWidgetsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWidgetsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Widgets().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWidgetsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WidgetSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWidgetsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WidgetExists(ctx, tx, o.WidgetID)
	if err != nil {
		t.Errorf("Unable to check if Widget exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WidgetExists to return true, but got false.")
	}
}

func testWidgetsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	widgetFound, err := FindWidget(ctx, tx, o.WidgetID)
	if err != nil {
		t.Error(err)
	}

	if widgetFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWidgetsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Widgets().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWidgetsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Widgets().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWidgetsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	widgetOne := &Widget{}
	widgetTwo := &Widget{}
	if err = randomize.Struct(seed, widgetOne, widgetDBTypes, false, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}
	if err = randomize.Struct(seed, widgetTwo, widgetDBTypes, false, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = widgetOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = widgetTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Widgets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWidgetsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	widgetOne := &Widget{}
	widgetTwo := &Widget{}
	if err = randomize.Struct(seed, widgetOne, widgetDBTypes, false, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}
	if err = randomize.Struct(seed, widgetTwo, widgetDBTypes, false, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = widgetOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = widgetTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func widgetBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Widget) error {
	*o = Widget{}
	return nil
}

func widgetAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Widget) error {
	*o = Widget{}
	return nil
}

func widgetAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Widget) error {
	*o = Widget{}
	return nil
}

func widgetBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Widget) error {
	*o = Widget{}
	return nil
}

func widgetAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Widget) error {
	*o = Widget{}
	return nil
}

func widgetBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Widget) error {
	*o = Widget{}
	return nil
}

func widgetAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Widget) error {
	*o = Widget{}
	return nil
}

func widgetBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Widget) error {
	*o = Widget{}
	return nil
}

func widgetAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Widget) error {
	*o = Widget{}
	return nil
}

func testWidgetsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Widget{}
	o := &Widget{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, widgetDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Widget object: %s", err)
	}

	AddWidgetHook(boil.BeforeInsertHook, widgetBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	widgetBeforeInsertHooks = []WidgetHook{}

	AddWidgetHook(boil.AfterInsertHook, widgetAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	widgetAfterInsertHooks = []WidgetHook{}

	AddWidgetHook(boil.AfterSelectHook, widgetAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	widgetAfterSelectHooks = []WidgetHook{}

	AddWidgetHook(boil.BeforeUpdateHook, widgetBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	widgetBeforeUpdateHooks = []WidgetHook{}

	AddWidgetHook(boil.AfterUpdateHook, widgetAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	widgetAfterUpdateHooks = []WidgetHook{}

	AddWidgetHook(boil.BeforeDeleteHook, widgetBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	widgetBeforeDeleteHooks = []WidgetHook{}

	AddWidgetHook(boil.AfterDeleteHook, widgetAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	widgetAfterDeleteHooks = []WidgetHook{}

	AddWidgetHook(boil.BeforeUpsertHook, widgetBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	widgetBeforeUpsertHooks = []WidgetHook{}

	AddWidgetHook(boil.AfterUpsertHook, widgetAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	widgetAfterUpsertHooks = []WidgetHook{}
}

func testWidgetsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWidgetsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(widgetColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWidgetToManyWidgetTags(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Widget
	var b, c WidgetTag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, widgetTagDBTypes, false, widgetTagColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, widgetTagDBTypes, false, widgetTagColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.WidgetID = a.WidgetID
	c.WidgetID = a.WidgetID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.WidgetTags().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.WidgetID == b.WidgetID {
			bFound = true
		}
		if v.WidgetID == c.WidgetID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := WidgetSlice{&a}
	if err = a.L.LoadWidgetTags(ctx, tx, false, (*[]*Widget)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WidgetTags); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.WidgetTags = nil
	if err = a.L.LoadWidgetTags(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WidgetTags); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testWidgetToManyAddOpWidgetTags(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Widget
	var b, c, d, e WidgetTag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, widgetDBTypes, false, strmangle.SetComplement(widgetPrimaryKeyColumns, widgetColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WidgetTag{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, widgetTagDBTypes, false, strmangle.SetComplement(widgetTagPrimaryKeyColumns, widgetTagColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*WidgetTag{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddWidgetTags(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.WidgetID != first.WidgetID {
			t.Error("foreign key was wrong value", a.WidgetID, first.WidgetID)
		}
		if a.WidgetID != second.WidgetID {
			t.Error("foreign key was wrong value", a.WidgetID, second.WidgetID)
		}

		if first.R.Widget != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Widget != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.WidgetTags[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.WidgetTags[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.WidgetTags().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testWidgetsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWidgetsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WidgetSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWidgetsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Widgets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	widgetDBTypes = map[string]string{`WidgetID`: `varchar`, `Name`: `varchar`, `Description`: `text`}
	_             = bytes.MinRead
)

func testWidgetsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(widgetPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(widgetAllColumns) == len(widgetPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWidgetsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(widgetAllColumns) == len(widgetPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Widget{}
	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, widgetDBTypes, true, widgetPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(widgetAllColumns, widgetPrimaryKeyColumns) {
		fields = widgetAllColumns
	} else {
		fields = strmangle.SetComplement(
			widgetAllColumns,
			widgetPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WidgetSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWidgetsUpsert(t *testing.T) {
	t.Parallel()

	if len(widgetAllColumns) == len(widgetPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLWidgetUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Widget{}
	if err = randomize.Struct(seed, &o, widgetDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Widget: %s", err)
	}

	count, err := Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, widgetDBTypes, false, widgetPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Widget struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Widget: %s", err)
	}

	count, err = Widgets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
